package day08

import FileUtil.readInputFileToList
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test

class Day08Test {
    @Test
    fun `part 1 with test input`() {
        part1(testInput) shouldBe 14
    }

    @Test
    fun `part 1 with real input`() {
        part1(readInputFileToList("day08.txt")) shouldBe 390
    }

    @Test
    fun `part 2 with test input`() {
        part2(testInput) shouldBe 34
    }

    @Test
    fun `part 2 with real input`() {
        part2(readInputFileToList("day08.txt")) shouldBe 1246
    }

    @Test
    fun `finds antinodes of two antennae`() {
        AntennaMap.parse(
            """
                ..........
                ..........
                ..........
                ....a.....
                ..........
                .....a....
                ..........
                ..........
                ..........
                ..........
            """).showAntinodesAsString() shouldBe
            """
                ..........
                ...#......
                ..........
                ....a.....
                ..........
                .....a....
                ..........
                ......#...
                ..........
                ..........
            """.trimIndent()
    }

    @Test
    fun `finds antinodes of three antennae`() {
        AntennaMap.parse(
            """
                ..........
                ..........
                ..........
                ....a.....
                ........a.
                .....a....
                ..........
                ..........
                ..........
                ..........
            """).showAntinodesAsString() shouldBe """
                ..........
                ...#......
                #.........
                ....a.....
                ........a.
                .....a....
                ..#.......
                ......#...
                ..........
                ..........
            """.trimIndent()
    }

}

val testInput =
    """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent().lines()
